name: 'qualification-issue-creation'
description: 'FSR qualification workflow automation'
author: 'GoFAIR Foundation'

# Define your inputs here.
# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'
steps:
  - name: My action
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


runs:
  using: node20
  main: dist/index.js
